import pg from 'pg';
import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { getControlPool, encryptCredential, closeTenantPool } from '../../../packages/db/src/router.js';

const { Client } = pg;
const __dirname = path.dirname(fileURLToPath(import.meta.url));

export type TenantType = 'individual' | 'agency';

export interface ProvisionInput {
  type: TenantType;
  displayName: string;
  ownerEmail?: string;
  parentAgencyId?: string | null;
  region?: string;
}

export interface ProvisionResult {
  tenantId: string;
  dbName: string;
  dbRole: string;
}

/** Generate a safe, unique database + role name. */
function makeNames(type: TenantType): { dbName: string; dbRole: string } {
  const prefix = process.env.TENANT_DB_PREFIX || 'fnnlr_tenant';
  const suffix = crypto.randomBytes(6).toString('hex');
  const base = `${prefix}_${type}_${suffix}`;
  return { dbName: base, dbRole: `${base}_role` };
}

function tenantSchemaSqls(): { version: string; sql: string }[] {
  const dir = path.join(__dirname, '../../../packages/db/tenant/migrations');
  return fs.readdirSync(dir).filter((f) => f.endsWith('.sql')).sort().map((f) => ({
    version: f.replace('.sql', ''),
    sql: fs.readFileSync(path.join(dir, f), 'utf8'),
  }));
}

/**
 * Provision a brand-new, physically isolated database for a tenant.
 *
 * Steps:
 *  1. Register the tenant in the control-plane (status = provisioning).
 *  2. As an admin role, CREATE ROLE + CREATE DATABASE owned by that role.
 *  3. Connect to the NEW database and apply the tenant schema.
 *  4. Mark the tenant active and record its schema version.
 *
 * The new database is owned by a dedicated role with a unique password,
 * so nothing else in the system can connect to it by accident.
 */
export async function provisionTenant(input: ProvisionInput): Promise<ProvisionResult> {
  const control = getControlPool();
  const host = process.env.TENANT_DB_HOST || 'localhost';
  const port = Number(process.env.TENANT_DB_PORT || 5432);
  const adminUrl = process.env.TENANT_DB_ADMIN_URL;
  if (!adminUrl) throw new Error('TENANT_DB_ADMIN_URL is not set');

  const { dbName, dbRole } = makeNames(input.type);
  const password = crypto.randomBytes(18).toString('base64url');
  const encrypted = encryptCredential(password);

  // 1) Register in control-plane (provisioning).
  const reg = await control.query(
    `INSERT INTO tenants
       (type, status, display_name, db_host, db_port, db_name, db_role, db_credential, region, parent_agency_id)
     VALUES ($1,'provisioning',$2,$3,$4,$5,$6,$7,$8,$9)
     RETURNING id`,
    [input.type, input.displayName, host, port, dbName, dbRole, encrypted,
     input.region || 'eu-central', input.parentAgencyId || null],
  );
  const tenantId: string = reg.rows[0].id;

  await control.query(
    `INSERT INTO control_audit (actor, action, tenant_id, detail)
     VALUES ('system','provision',$1,$2)`,
    [tenantId, JSON.stringify({ dbName, type: input.type })],
  );

  // 2) Create the dedicated role + database using the admin connection.
  //    (CREATE DATABASE cannot run inside a transaction block.)
  const admin = new Client({ connectionString: adminUrl });
  await admin.connect();
  try {
    // Role names/identifiers are generated by us (not user input) so are safe to inline,
    // but we still validate the shape defensively.
    if (!/^[a-z0-9_]+$/.test(dbName) || !/^[a-z0-9_]+$/.test(dbRole)) {
      throw new Error('Generated identifiers failed validation');
    }
    await admin.query(`CREATE ROLE ${dbRole} LOGIN PASSWORD '${password.replace(/'/g, "''")}'`);
    await admin.query(`CREATE DATABASE ${dbName} OWNER ${dbRole}`);
    // Lock it down: only the dedicated role may use this DB.
    await admin.query(`REVOKE ALL ON DATABASE ${dbName} FROM PUBLIC`);
    await admin.query(`GRANT ALL ON DATABASE ${dbName} TO ${dbRole}`);
  } finally {
    await admin.end();
  }

  // 3) Apply the tenant schema inside the NEW database, connecting as the dedicated role.
  const tenantClient = new Client({ host, port, database: dbName, user: dbRole, password });
  await tenantClient.connect();
  try {
    const migrations = tenantSchemaSqls();
    let lastVersion = '0001_init_tenant_schema';
    for (const m of migrations) {
      await tenantClient.query(m.sql);
      await tenantClient.query(
        `INSERT INTO schema_migrations_tenant (version) VALUES ($1) ON CONFLICT DO NOTHING`,
        [m.version],
      );
      lastVersion = m.version;
    }
    // For an individual tenant, seed the single business automatically.
    if (input.type === 'individual') {
      await tenantClient.query(
        `INSERT INTO businesses (name) VALUES ($1)`,
        [input.displayName],
      );
    }
  } finally {
    await tenantClient.end();
  }

  // 4) Mark active + record migration status + map the owner user.
  await control.query(`UPDATE tenants SET status='active', updated_at=now() WHERE id=$1`, [tenantId]);
  await control.query(
    `INSERT INTO tenant_migration_status (tenant_id, schema_version) VALUES ($1,'0001_init_tenant_schema')
     ON CONFLICT (tenant_id) DO UPDATE SET schema_version=EXCLUDED.schema_version, last_migrated_at=now()`,
    [tenantId],
  );
  if (input.ownerEmail) {
    await control.query(
      `INSERT INTO tenant_users (tenant_id, email, role)
       VALUES ($1,$2,$3) ON CONFLICT DO NOTHING`,
      [tenantId, input.ownerEmail, input.type === 'agency' ? 'agency_admin' : 'owner'],
    );
  }

  return { tenantId, dbName, dbRole };
}

/**
 * Delete a tenant: drop its dedicated database entirely.
 * Total isolation makes "right to be forgotten" complete and verifiable —
 * the data does not exist anywhere else.
 */
export async function deleteTenant(tenantId: string): Promise<void> {
  const control = getControlPool();
  const res = await control.query(`SELECT db_name, db_role FROM tenants WHERE id=$1`, [tenantId]);
  if (res.rowCount === 0) throw new Error(`Tenant not found: ${tenantId}`);
  const { db_name: dbName, db_role: dbRole } = res.rows[0];

  await control.query(`UPDATE tenants SET status='deleting', updated_at=now() WHERE id=$1`, [tenantId]);

  // close the app-side pool first so we don't leave connections that error when the DB drops
  await closeTenantPool(tenantId).catch(() => { /* pool may not exist */ });

  const adminUrl = process.env.TENANT_DB_ADMIN_URL!;
  const admin = new Client({ connectionString: adminUrl });
  await admin.connect();
  try {
    // Terminate connections, then drop DB + role.
    await admin.query(
      `SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=$1`,
      [dbName],
    );
    await admin.query(`DROP DATABASE IF EXISTS ${dbName}`);
    await admin.query(`DROP ROLE IF EXISTS ${dbRole}`);
  } finally {
    await admin.end();
  }

  await control.query(
    `UPDATE tenants SET status='deleted', deleted_at=now(), updated_at=now() WHERE id=$1`,
    [tenantId],
  );
  await control.query(
    `INSERT INTO control_audit (actor, action, tenant_id, detail)
     VALUES ('system','delete',$1,$2)`,
    [tenantId, JSON.stringify({ dbName })],
  );
}
