#!/usr/bin/env tsx
import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const runDir = 'gateforge-audit/run-2026-06-23-1035';
const dirIndex = process.argv.indexOf('--dir');
const secretDir = dirIndex >= 0 ? process.argv[dirIndex + 1] : '/tmp/fnnlr-gateforge-secrets';
const outIndex = process.argv.indexOf('--out');
const outPath = outIndex >= 0 ? process.argv[outIndex + 1] : `${runDir}/45_secret_replacement_packet.md`;
const csvIndex = process.argv.indexOf('--csv-out');
const csvPath = csvIndex >= 0 ? process.argv[csvIndex + 1] : `${runDir}/45_secret_replacement_packet.csv`;

type SecretStatus = 'READY' | 'MISSING' | 'EMPTY' | 'PLACEHOLDER' | 'INVALID';
type SecretKind = 'runtime' | 'attestation';
type SecretEntry = {
  name: string;
  kind: SecretKind;
  status: SecretStatus;
  reason?: string;
};
type LocalSecretSummary = {
  ok: boolean;
  directory: string;
  attestationReady: number;
  attestationRequired: number;
  attestationOptions: SecretEntry[];
  runtimeReady: number;
  runtimeRequired: number;
  runtime: SecretEntry[];
};

type ReplacementRow = SecretEntry & {
  source: string;
  requiredAction: string;
  validation: string;
  uploadPhase: string;
};

const sourceBySecret: Record<string, string> = {
  GATEFORGE_HOSTED_STAGING_ATTESTATION_JSON: 'Generated by hosted strict workflow or operator from hosted-staging-attestation.json.',
  GATEFORGE_HOSTED_STAGING_ATTESTATION_B64: 'Base64 of hosted-staging-attestation.json after real staging evidence is collected.',
  CONTROL_PLANE_DATABASE_URL: 'Staging Postgres control-plane database URL from the hosting/provider console.',
  TENANT_DB_ADMIN_URL: 'Staging Postgres admin URL with tenant database create/drop permissions.',
  TENANT_DB_HOST: 'Staging tenant database host only, without credentials.',
  TENANT_CREDENTIAL_ENCRYPTION_KEY: 'Generated staging-only secret from gateforge:scaffold-local-secrets.',
  INTEGRATION_ENCRYPTION_KEY: 'Generated staging-only secret from gateforge:scaffold-local-secrets.',
  FNNLR_CRON_SECRET: 'Generated staging-only cron secret from gateforge:scaffold-local-secrets.',
  AUTH_MFA_ENCRYPTION_KEY: 'Generated staging-only MFA encryption secret from gateforge:scaffold-local-secrets.',
  FNNLR_AI_TENANT_DAILY_USD_CAP: 'Operator-approved staging AI tenant daily budget cap.',
  FNNLR_AI_GLOBAL_DAILY_USD_CAP: 'Operator-approved staging AI global daily budget cap.',
  SENTRY_DSN: 'Staging Sentry project DSN or equivalent error alerting DSN.',
  UPTIME_HEALTHCHECK_URL: 'Public staging /health uptime check URL.',
  ALERT_EMAIL_TO: 'Operations email for staging alert delivery.',
  ALERT_WEBHOOK_URL: 'Staging alert webhook URL for cron/webhook failure notifications.',
  RESEND_API_KEY: 'Resend staging API key or equivalent transactional email provider key.',
  EMAIL_FROM: 'Verified transactional sender address for staging.',
  EMAIL_REPLY_TO: 'Support reply-to mailbox for staging emails.',
  ANTHROPIC_API_KEY: 'Staging Anthropic provider key with spend caps enabled.',
};

function runLocalCheck(): { status: number; output: string } {
  const result = spawnSync('npx', ['tsx', 'scripts/gateforge-local-secret-files-check.ts', '--dir', secretDir, '--json'], {
    encoding: 'utf8',
    maxBuffer: 1024 * 1024,
    stdio: ['ignore', 'pipe', 'pipe'],
  });
  return {
    status: result.status ?? 1,
    output: `${result.stdout || ''}${result.stderr || ''}`,
  };
}

function actionFor(entry: SecretEntry): string {
  if (entry.status === 'READY') return 'No replacement needed. Keep the file private and upload only through the safe uploader.';
  if (entry.status === 'MISSING' && entry.kind === 'attestation') {
    return `Optional if the other attestation option is READY; otherwise create ${path.join(secretDir, entry.name)} from real staging evidence.`;
  }
  if (entry.status === 'MISSING') return `Create ${path.join(secretDir, entry.name)} with the real staging value.`;
  if (entry.status === 'EMPTY') return `Replace the empty file ${path.join(secretDir, entry.name)} with the real staging value.`;
  if (entry.status === 'INVALID') return `Replace ${path.join(secretDir, entry.name)} with a valid real staging value.`;
  return `Replace the placeholder in ${path.join(secretDir, entry.name)} with the real staging value.`;
}

function validationFor(entry: SecretEntry): string {
  if (entry.kind === 'attestation') return 'At least one attestation file must become READY; then run npm run gateforge:local-secret-files-check.';
  if (entry.name.includes('DATABASE_URL') || entry.name === 'TENANT_DB_ADMIN_URL') return 'Must be a real staging Postgres URL; then run npm run gateforge:hosted-unblock -- --dry-run.';
  if (entry.name === 'TENANT_DB_HOST') return 'Must be the staging database host only; then run npm run gateforge:local-secret-files-check.';
  if (entry.name.includes('CAP')) return 'Must be a numeric staging spend cap; then run npm run gateforge:local-secret-files-check.';
  if (entry.name.includes('EMAIL')) return 'Must match the staging transactional email setup; then run hosted strict evidence.';
  if (entry.name.includes('URL') || entry.name.includes('DSN')) return 'Must point to staging observability/alerting infrastructure; then run hosted strict evidence.';
  return 'Run npm run gateforge:local-secret-files-check after replacement.';
}

function uploadPhaseFor(entry: SecretEntry): string {
  if (entry.status === 'READY') return 'Ready for safe upload';
  if (entry.kind === 'attestation') return 'Replace after hosted staging evidence packet exists';
  return 'Replace before GitHub secret upload';
}

function csvEscape(value: string): string {
  return `"${value.replace(/"/g, '""')}"`;
}

function markdownEscape(value: string): string {
  return value.replace(/\|/g, '\\|');
}

const check = runLocalCheck();
let summary: LocalSecretSummary;
try {
  summary = JSON.parse(check.output) as LocalSecretSummary;
} catch {
  console.error('GateForge secret replacement packet: FAIL - could not parse local secret check JSON');
  console.error('No secret values were printed.');
  process.exit(1);
}

const rows: ReplacementRow[] = [...summary.attestationOptions, ...summary.runtime].map((entry) => ({
  ...entry,
  source: sourceBySecret[entry.name] ?? 'Operator-provided staging secret.',
  requiredAction: actionFor(entry),
  validation: validationFor(entry),
  uploadPhase: uploadPhaseFor(entry),
}));

const blockers = rows.filter((row) => row.status !== 'READY');
const replacementCount = blockers.filter((row) => row.status === 'PLACEHOLDER' || row.status === 'EMPTY' || row.status === 'MISSING' || row.status === 'INVALID').length;
const runtimeReplacementCount = summary.runtime.filter((row) => row.status !== 'READY').length;
const attestationSatisfied = summary.attestationReady >= summary.attestationRequired;
const decision = summary.ok ? 'READY_FOR_UPLOAD' : 'REPLACE_LOCAL_SECRET_VALUES';
const now = new Date().toISOString();

const table = rows
  .map(
    (row) =>
      `| \`${row.name}\` | \`${row.kind}\` | \`${row.status}\` | ${markdownEscape(row.reason ?? '')} | ${markdownEscape(row.source)} | ${markdownEscape(row.requiredAction)} | ${markdownEscape(row.validation)} | ${markdownEscape(row.uploadPhase)} |`,
  )
  .join('\n');

const body = `# GateForge Secret Replacement Packet

Generated: \`${now}\`

This packet is sanitized. It reports secret file names and readiness states only. No secret values were printed or copied.

## Decision

- Status: \`${decision}\`
- Local secret directory: \`${secretDir}\`
- Runtime ready: \`${summary.runtimeReady}/${summary.runtimeRequired}\`
- Attestation ready: \`${summary.attestationReady}/${summary.attestationRequired}\`
- Runtime replacements remaining: \`${runtimeReplacementCount}\`
- Attestation satisfied: \`${attestationSatisfied ? 'YES' : 'NO'}\`
- Open secret rows listed: \`${replacementCount}\`

## Immediate Command Path

1. Replace every runtime \`MISSING\`, \`EMPTY\`, \`PLACEHOLDER\`, or \`INVALID\` file listed below with the real staging value.
2. Make at least one attestation option \`READY\`; \`GATEFORGE_HOSTED_STAGING_ATTESTATION_B64\` is preferred, so \`GATEFORGE_HOSTED_STAGING_ATTESTATION_JSON\` may remain \`MISSING\` if B64 is ready.
3. Run \`npm run gateforge:local-secret-files-check\`.
4. Run \`npm run gateforge:hosted-readiness-doctor\`.
5. When the doctor says \`UPLOAD_GITHUB_SECRETS\`, run \`npm run gateforge:hosted-unblock -- --apply\`.
6. When hosted strict evidence finishes, run \`npm run gateforge:final-gate\` and \`npm run gateforge:final-report\`.

## Replacement Matrix

| Secret | Kind | Status | Reason | Source | Required action | Validation | Upload phase |
| --- | --- | --- | --- | --- | --- | --- | --- |
${table}

## Hard Rules

- Do not upload while any runtime secret is \`MISSING\`, \`EMPTY\`, \`PLACEHOLDER\`, or \`INVALID\`.
- At least one attestation option must be \`READY\`; \`GATEFORGE_HOSTED_STAGING_ATTESTATION_B64\` is the preferred upload format.
- Do not paste secret values into reports, Git commits, issues, or chat.
- If a provider value does not exist yet, keep the item open instead of using fake data.
`;

const csvHeader = ['secret', 'kind', 'status', 'reason', 'source', 'required_action', 'validation', 'upload_phase'];
const csvRows = rows.map((row) =>
  [row.name, row.kind, row.status, row.reason ?? '', row.source, row.requiredAction, row.validation, row.uploadPhase].map(csvEscape).join(','),
);

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, body);
fs.writeFileSync(csvPath, `${csvHeader.join(',')}\n${csvRows.join('\n')}\n`);

console.log(`GateForge secret replacement packet: ${decision}`);
console.log(`  wrote ${outPath}`);
console.log(`  wrote ${csvPath}`);
console.log('  No secret values were printed.');

if (!summary.ok) process.exit(1);
